In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

%matplotlib inline

In [2]:
dbDiabetes = pd.read_csv('datos/diabetes.csv')

In [45]:
X = dbDiabetes[['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']]
Y = dbDiabetes['Y']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [46]:
scaler = StandardScaler()

In [47]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [48]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
mlp = MLPClassifier(hidden_layer_sizes=(10,20,20),max_iter=1000)

In [50]:
mlp.fit(X_train,Y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 20, 20), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [51]:
predictions = mlp.predict(X_test)

In [52]:


print(confusion_matrix(Y_test,predictions))



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [53]:
print(classification_report(Y_test,predictions))

              precision    recall  f1-score   support

        42.0       0.00      0.00      0.00         1
        47.0       0.00      0.00      0.00         0
        49.0       0.00      0.00      0.00         1
        51.0       0.00      0.00      0.00         0
        57.0       0.00      0.00      0.00         1
        59.0       0.00      0.00      0.00         0
        60.0       0.00      0.00      0.00         0
        63.0       0.00      0.00      0.00         1
        64.0       0.00      0.00      0.00         0
        65.0       0.00      0.00      0.00         0
        66.0       0.00      0.00      0.00         2
        68.0       0.00      0.00      0.00         1
        72.0       0.00      0.00      0.00         1
        77.0       0.00      0.00      0.00         0
        81.0       0.00      0.00      0.00         1
        83.0       0.00      0.00      0.00         1
        84.0       0.00      0.00      0.00         1
        85.0       0.00    

/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/root/anaconda3/lib/python3.